version: "3.8"
services:

  react:
    image: rating-app
    container_name: rating-app
    restart: always
    depends_on: 
      - api
    build:
      context: ./rating-app
      dockerfile: Dockerfile
    ports:
      - 3000:80
    networks:
      - frontend
      - backend

  api:
    image: api
    container_name: api
    restart: always
    depends_on: 
      - postgres_db
    build:
      context: ./web-api
      dockerfile: Dockerfile
    ports:
      - 7156:80
    networks:
      - backend

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - backend
      
networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge